baseURL = "https://ewynx.github.io/panaderia-xilonem/"
title = "Panaderia Xilonem"
DefaultContentLanguage = "es"
publishDir = "docs"

[languages]
[languages.en]
weight = 2
languageName = "English"

[languages.es]
weight = 1
languageName = "Español"
